destroyScheduledDuration: 2592000s
name: projects/lab-gke-se/locations/us-central1/keyRings/LAB-GKE-SE-gke-key-ring-npkh/cryptoKeys/LAB-GKE-SE-gke-key
primary:
  algorithm: GOOGLE_SYMMETRIC_ENCRYPTION
  name: projects/lab-gke-se/locations/us-central1/keyRings/LAB-GKE-SE-gke-key-ring-npkh/cryptoKeys/LAB-GKE-SE-gke-key/cryptoKeyVersions/1
  protectionLevel: HSM
  state: ENABLED
purpose: ENCRYPT_DECRYPT
versionTemplate:
  algorithm: GOOGLE_SYMMETRIC_ENCRYPTION
  protectionLevel: HSM
