name: tenant-gke-cluster-usc1
description: Private Autopilot Cluster with Public Endpoint

addonsConfig:
  dnsCacheConfig:
    enabled: true
  gcePersistentDiskCsiDriverConfig:
    enabled: true
  gcpFilestoreCsiDriverConfig:
    enabled: true
  gcsFuseCsiDriverConfig:
    enabled: true
  horizontalPodAutoscaling: {}
  httpLoadBalancing: {}
  kubernetesDashboard:
    disabled: true
  networkPolicyConfig:
    disabled: true
  statefulHaConfig:
    enabled: true
    
autopilot:
  enabled: true

autoscaling:
  autoprovisioningNodePoolDefaults:
    bootDiskKmsKey: ${kms_key_prj_tenant_2}
    serviceAccount: ${service_account}

currentMasterVersion: 1.29.7-gke.1274000
currentNodeVersion: 1.29.6-gke.1038001

databaseEncryption:
  currentState: CURRENT_STATE_ENCRYPTED
  keyName: ${kms_key_prj_tenant_2}
  state: ENCRYPTED

ipAllocationPolicy:
  clusterSecondaryRangeName: tenant-gke-pods
  servicesSecondaryRangeName: tenant-gke-services
  stackType: IPV4
  useIpAliases: true

location: us-central1
locations:
- us-central1-a
- us-central1-b
- us-central1-c
- us-central1-f

loggingConfig:
  componentConfig:
    enableComponents:
    # Default  
    - SYSTEM_COMPONENTS
    - WORKLOADS
    # Additional 
    - CONTROLLER_MANAGER
    - SCHEDULER
    - APISERVER
loggingService: logging.googleapis.com/kubernetes

masterAuthorizedNetworksConfig:
  cidrBlocks:
  - cidrBlock: 217.8.23.33/32
    displayName: Himanshu's Home
  - cidrBlock: 10.10.1.0/25
    displayName: Bastion
  - cidrBlock: 10.10.2.0/24
    displayName: vdi
  - cidrBlock: 161.124.14.0/24
    displayName: pupi
  - cidrBlock: 77.101.187.225/32
    displayName: Dave's Home
  - cidrBlock: 176.26.156.96/32
    displayName: Vino's Home
  - cidrBlock: 34.90.34.165/32
    displayName: cloud shell (temp)
  enabled: true
  gcpPublicCidrsAccessEnabled: false

monitoringConfig:
  advancedDatapathObservabilityConfig:
    enableMetrics: true
  componentConfig:
    enableComponents:
    - SYSTEM_COMPONENTS
    - POD
    - DAEMONSET
    - DEPLOYMENT
    - STATEFULSET
    - STORAGE
    - HPA
    - CADVISOR
    - KUBELET
  managedPrometheusConfig:
    enabled: true
monitoringService: monitoring.googleapis.com/kubernetes

maintenancePolicy:
  resourceVersion: ce912209
  window:
    dailyMaintenanceWindow:
      duration: PT4H0M0S
      startTime: 05:00

network: projects/lab-gke-se/global/networks/dev-network

nodeConfig:
  bootDiskKmsKey: projects/lab-gke-se/locations/us-central1/keyRings/LAB-GKE-SE-gke-key-ring-npkh/cryptoKeys/LAB-GKE-SE-gke-key
  diskSizeGb: 100
  diskType: pd-balanced
  imageType: COS_CONTAINERD
  machineType: e2-small
  metadata:
    disable-legacy-endpoints: 'true'
  oauthScopes:
  - https://www.googleapis.com/auth/userinfo.email
  - https://www.googleapis.com/auth/cloud-platform
  reservationAffinity:
    consumeReservationType: NO_RESERVATION
  serviceAccount: gke-cluster@lab-gke-se.iam.gserviceaccount.com
  shieldedInstanceConfig:
    enableIntegrityMonitoring: true
    enableSecureBoot: true
  taints:
  - effect: NO_SCHEDULE
    key: cloud.google.com/gke-quick-remove
    value: 'true'
  windowsNodeConfig: {}
  workloadMetadataConfig:
    mode: GKE_METADATA

privateClusterConfig:
  enablePrivateEndpoint: false
  enablePrivateNodes: true
  masterGlobalAccessConfig:
    enabled: true

releaseChannel:
  channel: REGULAR

subnetwork: projects/lab-gke-se/regions/us-central1/subnetworks/tenant-gke-us-central1

verticalPodAutoscaling:
  enabled: true

