addonsConfig:
  configConnectorConfig: {}
  dnsCacheConfig:
    enabled: true
  gcePersistentDiskCsiDriverConfig:
    enabled: true
  gcpFilestoreCsiDriverConfig: {}
  gcsFuseCsiDriverConfig:
    enabled: true
  gkeBackupAgentConfig: {}
  horizontalPodAutoscaling: {}
  httpLoadBalancing: {}
  kubernetesDashboard:
    disabled: true
  networkPolicyConfig:
    disabled: true
autopilot: {}
autoscaling:
  autoprovisioningNodePoolDefaults:
    diskSizeGb: 100
    diskType: pd-standard
    imageType: COS_CONTAINERD
    management:
      autoRepair: true
      autoUpgrade: true
      upgradeOptions: {}
    oauthScopes:
    - https://www.googleapis.com/auth/cloud-platform
    serviceAccount: gke-node-sa@lab-gke-se.iam.gserviceaccount.com
    shieldedInstanceConfig:
      enableIntegrityMonitoring: true
    upgradeSettings:
      strategy: SURGE
  autoscalingProfile: BALANCED
  enableNodeAutoprovisioning: true
  resourceLimits:
  - maximum: '64'
    minimum: '8'
    resourceType: cpu
  - maximum: '128'
    minimum: '10'
    resourceType: memory
binaryAuthorization: {}
clusterIpv4Cidr: 240.12.64.0/19
controlPlaneEndpointsConfig:
  dnsEndpointConfig:
    allowExternalTraffic: true
    endpoint: gke-6db971f8a2a4499eb609d155970ddd89782a-52991355109.us-east4.gke.goog
  ipEndpointsConfig:
    authorizedNetworksConfig:
      cidrBlocks:
      - cidrBlock: 10.10.2.0/24
        displayName: VDI
      - cidrBlock: 34.90.34.165/32
        displayName: cloud shell (temp)
      - cidrBlock: 176.26.156.96/32
        displayName: Vino's Home
      - cidrBlock: 161.124.14.0/24
        displayName: pupi
      - cidrBlock: 10.10.1.0/25
        displayName: Bastion
      - cidrBlock: 2.100.85.15/32
        displayName: Himanshu's Home
      - cidrBlock: 77.101.187.225/32
        displayName: Dave's Home
      enabled: true
      privateEndpointEnforcementEnabled: true
    enablePublicEndpoint: true
    enabled: true
    privateEndpoint: 10.252.1.2
    privateEndpointSubnetwork: projects/lab-gke-se/regions/us-east4/subnetworks/gke-gke-std-go76-069b5a12-pe-subnet
    publicEndpoint: 34.21.0.111
createTime: '2024-10-02T07:22:55+00:00'
currentMasterVersion: 1.30.5-gke.1014001
currentNodeCount: 2
currentNodeVersion: 1.30.5-gke.1014001
databaseEncryption:
  currentState: CURRENT_STATE_ENCRYPTED
  keyName: projects/lab-gke-se/locations/us-east4/keyRings/lab-gke-std-keyring-08/cryptoKeys/lab-gke-std-key-08
  state: ENCRYPTED
defaultMaxPodsConstraint:
  maxPodsPerNode: '110'
endpoint: 34.21.0.111
enterpriseConfig:
  clusterTier: STANDARD
etag: b984c0e5-6185-4e4b-a8db-9912ec12a035
id: 6db971f8a2a4499eb609d155970ddd89782a031a473a435f86e5ee3c331ebd3c
initialClusterVersion: 1.30.3-gke.1969001
instanceGroupUrls:
- https://www.googleapis.com/compute/v1/projects/lab-gke-se/zones/us-east4-a/instanceGroupManagers/gke-gke-std-go76-platform-np-1-f9dacd21-grp
- https://www.googleapis.com/compute/v1/projects/lab-gke-se/zones/us-east4-b/instanceGroupManagers/gke-gke-std-go76-platform-np-1-daa5cbe8-grp
- https://www.googleapis.com/compute/v1/projects/lab-gke-se/zones/us-east4-c/instanceGroupManagers/gke-gke-std-go76-platform-np-1-cfa91f21-grp
- https://www.googleapis.com/compute/v1/projects/lab-gke-se/zones/us-east4-a/instanceGroupManagers/gke-gke-std-go76-application-np-1-f821ed1a-grp
- https://www.googleapis.com/compute/v1/projects/lab-gke-se/zones/us-east4-b/instanceGroupManagers/gke-gke-std-go76-application-np-1-423c19ea-grp
- https://www.googleapis.com/compute/v1/projects/lab-gke-se/zones/us-east4-c/instanceGroupManagers/gke-gke-std-go76-application-np-1-5477cdc2-grp
ipAllocationPolicy:
  clusterIpv4Cidr: 240.12.64.0/19
  clusterIpv4CidrBlock: 240.12.64.0/19
  clusterSecondaryRangeName: gke-pods
  defaultPodIpv4RangeUtilization: 0.0625
  podCidrOverprovisionConfig: {}
  servicesIpv4Cidr: 240.12.36.0/22
  servicesIpv4CidrBlock: 240.12.36.0/22
  servicesSecondaryRangeName: gke-services
  stackType: IPV4
  useIpAliases: true
labelFingerprint: 78cdf2f6
legacyAbac: {}
location: us-east4
locations:
- us-east4-a
- us-east4-b
- us-east4-c
loggingConfig:
  componentConfig:
    enableComponents:
    - SYSTEM_COMPONENTS
    - WORKLOADS
loggingService: logging.googleapis.com/kubernetes
maintenancePolicy:
  resourceVersion: ce912209
  window:
    dailyMaintenanceWindow:
      duration: PT4H0M0S
      startTime: 05:00
masterAuth:
  clientCertificateConfig: {}
  clusterCaCertificate: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMRENDQXBTZ0F3SUJBZ0lRVjJtc1d6Ry95bm1rT09mWTM1a0tKekFOQmdrcWhraUc5dzBCQVFzRkFEQXYKTVMwd0t3WURWUVFERXlSbE1UUTFZVFZpWlMwMk5HWXpMVFJoTm1ZdE9ESmpaaTFrTURNeU0ySTNNRFEyWkRZdwpJQmNOTWpReE1EQXlNRFl5TWpVMVdoZ1BNakExTkRBNU1qVXdOekl5TlRWYU1DOHhMVEFyQmdOVkJBTVRKR1V4Ck5EVmhOV0psTFRZMFpqTXROR0UyWmkwNE1tTm1MV1F3TXpJellqY3dORFprTmpDQ0FhSXdEUVlKS29aSWh2Y04KQVFFQkJRQURnZ0dQQURDQ0FZb0NnZ0dCQU1Za0pIVFluVkEra2RRWngxUG5yVWd5aVFMV3RTbmd3WUdFNk5acQphZE9HOGl2b3BFVzVpaEJWT0VxejNHZ1dUbW9wNUplYitGd2hFRWpRdTh5di9VZ3ZjOE5HQWtQK3VHYm5JVktFCkp1aEl0NngvV2NJUVFuaFFHL2dBSEx1bUROOWk4L2pkVEU2N2s5NzNnSlhSTmhvakRsRjBGeW1XR21Pd0pjR2EKVENUTzNHQy9kSnNvMWJBS1ZhMWExT1pwN3NicDRnSlA5aGRaMVRlSG13NDBaZGJIWGF5WXg4Skd5Q0xDeTk3egpQTXd6ODhpYjFCOTU5aXFUTnQyVnhaOHRpU0YwNmd6RWdNVStBcDJzVFArTWFKZlgwMU5Rd3dYbS9qR1orSm11Clc4elhyOEFvNlYzZXowaEQ5blBFK1l3Rk9TS1pqMVNVNkRkUFdhOWdXM1NiREdnM1pnODJhU1lsYmwyL3E0NXoKNmJJb09VZ0xRU1JrQzcvNzl2YWZCU0krRlBza3VSeGtBdUhIK2hrMEVoa0llKzV3aGJWR25yV2tucnB1ZHphSgpyZU9tNG9MWUFIZUIrWFJEajJkaGc3cW9zQkJpcW0xTDlQaXIrU1dsOXFRYjQrR1J2UTYrNmg1ZGlMK3hwNDg0Cmk3dllnY3h6Vk9GY0dXUy9pVm9pN2xmWGt3SURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQWdRd0R3WUQKVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVrT1NaRngwcUJOQXR4cmVHNDJ4YStRT3hKT3d3RFFZSgpLb1pJaHZjTkFRRUxCUUFEZ2dHQkFLYVZ5ekg5L21DVFNScTltOHZPQU9CdmR6SVY4YjRuUmMrNGtJN0JvS2pSCmlwS0JGbVVWYnRIZ3lvUjRvb0crb25iQUJOTjdoN2hLTHZBcmhSQlNOUW02OFFWa1JCOG4rNE44S3RhY0hranAKRkFJekV6RXdPeHprYjR5WFkya0lEWnVmeEp1c2xWTG56SGdqY254empuZjNDZFN4cDMwL1lOVmxtbVpMVXp1RgpLNFFhYjJieWlwVXEwSUpBLzhIWGp1YmtiMmo1TzlpdGw5V01MdDlmY0F3RHY4emhZS3dLMzNHQVI0SHB0d1RJCjVhZFhrTVppeVBjV1hsMENBcmdteUdHcnZFWnd6UzZPSG9nSk1aMnFjOUp5VlppK0lKOWU0SUtnUDVhdmRROEYKT2Z3MjNsUFBLQUpNZ0ZFMVhOTEFNekhQV00rVWxrYktPd3ZqVERlRzlHQkZDbi9rcDNid2kzdHJPT2FVU25LcgpxMEl6QVREQ3RhbUYxMExMdW53NXNOQmhhNzg3N01WUThJaW1QNWxkRnRpYU1ONitIR0NDUm5ZUEJtQUtObG9PCk0valg3Y0dZRHNXS0dPODdXd0VNNlBwR0Z0YVFPelJKcWNkeS9xdDcyL3hYRVVCM2RYaDM5K29vTnYrV3VidlEKVndYVTU2c3V6b0RoV25sNUVHSmU3dz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
masterAuthorizedNetworksConfig:
  cidrBlocks:
  - cidrBlock: 10.10.2.0/24
    displayName: VDI
  - cidrBlock: 34.90.34.165/32
    displayName: cloud shell (temp)
  - cidrBlock: 176.26.156.96/32
    displayName: Vino's Home
  - cidrBlock: 161.124.14.0/24
    displayName: pupi
  - cidrBlock: 10.10.1.0/25
    displayName: Bastion
  - cidrBlock: 2.100.85.15/32
    displayName: Himanshu's Home
  - cidrBlock: 77.101.187.225/32
    displayName: Dave's Home
  enabled: true
  privateEndpointEnforcementEnabled: true
meshCertificates:
  enableCertificates: false
monitoringConfig:
  advancedDatapathObservabilityConfig: {}
  componentConfig:
    enableComponents:
    - SYSTEM_COMPONENTS
    - DAEMONSET
    - DEPLOYMENT
    - STATEFULSET
    - STORAGE
    - HPA
    - POD
    - CADVISOR
    - KUBELET
  managedPrometheusConfig:
    enabled: true
monitoringService: monitoring.googleapis.com/kubernetes
name: gke-std-go76
network: dev-network
networkConfig:
  datapathProvider: ADVANCED_DATAPATH
  defaultEnablePrivateNodes: true
  defaultSnatStatus: {}
  dnsConfig:
    clusterDns: CLOUD_DNS
    clusterDnsScope: CLUSTER_SCOPE
  enableCiliumClusterwideNetworkPolicy: true
  gatewayApiConfig:
    channel: CHANNEL_STANDARD
  network: projects/lab-gke-se/global/networks/dev-network
  serviceExternalIpsConfig: {}
  subnetwork: projects/lab-gke-se/regions/us-east4/subnetworks/gke-std-go76
nodeConfig:
  diskSizeGb: 100
  diskType: pd-ssd
  effectiveCgroupMode: EFFECTIVE_CGROUP_MODE_V2
  imageType: COS_CONTAINERD
  labels:
    cluster_name: gke-std-go76
    node_pool: platform-np-1
  loggingConfig:
    variantConfig:
      variant: DEFAULT
  machineType: e2-standard-8
  metadata:
    cluster_name: gke-std-go76
    disable-legacy-endpoints: 'true'
    node_pool: platform-np-1
  oauthScopes:
  - https://www.googleapis.com/auth/cloud-platform
  serviceAccount: gke-node-sa@lab-gke-se.iam.gserviceaccount.com
  shieldedInstanceConfig:
    enableIntegrityMonitoring: true
  tags:
  - gke-gke-std-go76
  - gke-gke-std-go76-platform-np-1
  windowsNodeConfig: {}
  workloadMetadataConfig:
    mode: GKE_METADATA
nodePoolDefaults:
  nodeConfigDefaults:
    gcfsConfig: {}
    loggingConfig:
      variantConfig:
        variant: DEFAULT
    nodeKubeletConfig: {}
nodePools:
- autoscaling:
    enabled: true
    locationPolicy: BALANCED
    maxNodeCount: 10
  config:
    diskSizeGb: 100
    diskType: pd-ssd
    effectiveCgroupMode: EFFECTIVE_CGROUP_MODE_V2
    imageType: COS_CONTAINERD
    labels:
      cluster_name: gke-std-go76
      node_pool: platform-np-1
    loggingConfig:
      variantConfig:
        variant: DEFAULT
    machineType: e2-standard-8
    metadata:
      cluster_name: gke-std-go76
      disable-legacy-endpoints: 'true'
      node_pool: platform-np-1
    oauthScopes:
    - https://www.googleapis.com/auth/cloud-platform
    serviceAccount: gke-node-sa@lab-gke-se.iam.gserviceaccount.com
    shieldedInstanceConfig:
      enableIntegrityMonitoring: true
    tags:
    - gke-gke-std-go76
    - gke-gke-std-go76-platform-np-1
    windowsNodeConfig: {}
    workloadMetadataConfig:
      mode: GKE_METADATA
  etag: 16b89345-760d-4eb1-8eb2-ae8c9e5c5556
  initialNodeCount: 2
  instanceGroupUrls:
  - https://www.googleapis.com/compute/v1/projects/lab-gke-se/zones/us-east4-a/instanceGroupManagers/gke-gke-std-go76-platform-np-1-f9dacd21-grp
  - https://www.googleapis.com/compute/v1/projects/lab-gke-se/zones/us-east4-b/instanceGroupManagers/gke-gke-std-go76-platform-np-1-daa5cbe8-grp
  - https://www.googleapis.com/compute/v1/projects/lab-gke-se/zones/us-east4-c/instanceGroupManagers/gke-gke-std-go76-platform-np-1-cfa91f21-grp
  locations:
  - us-east4-a
  - us-east4-b
  - us-east4-c
  management:
    autoRepair: true
    autoUpgrade: true
  maxPodsConstraint:
    maxPodsPerNode: '110'
  name: platform-np-1
  networkConfig:
    enablePrivateNodes: true
    podIpv4CidrBlock: 240.12.64.0/19
    podIpv4RangeUtilization: 0.0625
    podRange: gke-pods
  podIpv4CidrSize: 24
  selfLink: https://container.googleapis.com/v1/projects/lab-gke-se/locations/us-east4/clusters/gke-std-go76/nodePools/platform-np-1
  status: RUNNING
  upgradeSettings:
    maxSurge: 1
    strategy: SURGE
  version: 1.30.5-gke.1014001
- autoscaling:
    enabled: true
    locationPolicy: BALANCED
    maxNodeCount: 1000
  config:
    diskSizeGb: 100
    diskType: pd-ssd
    effectiveCgroupMode: EFFECTIVE_CGROUP_MODE_V2
    imageType: COS_CONTAINERD
    labels:
      cluster_name: gke-std-go76
      node_pool: application-np-1
    loggingConfig:
      variantConfig:
        variant: DEFAULT
    machineType: e2-standard-16
    metadata:
      cluster_name: gke-std-go76
      disable-legacy-endpoints: 'true'
      node_pool: application-np-1
    oauthScopes:
    - https://www.googleapis.com/auth/cloud-platform
    serviceAccount: gke-node-sa@lab-gke-se.iam.gserviceaccount.com
    shieldedInstanceConfig:
      enableIntegrityMonitoring: true
    tags:
    - gke-gke-std-go76
    - gke-gke-std-go76-application-np-1
    windowsNodeConfig: {}
    workloadMetadataConfig:
      mode: GKE_METADATA
  etag: 5b228388-fde7-4d65-8177-a9fed37723b5
  instanceGroupUrls:
  - https://www.googleapis.com/compute/v1/projects/lab-gke-se/zones/us-east4-a/instanceGroupManagers/gke-gke-std-go76-application-np-1-f821ed1a-grp
  - https://www.googleapis.com/compute/v1/projects/lab-gke-se/zones/us-east4-b/instanceGroupManagers/gke-gke-std-go76-application-np-1-423c19ea-grp
  - https://www.googleapis.com/compute/v1/projects/lab-gke-se/zones/us-east4-c/instanceGroupManagers/gke-gke-std-go76-application-np-1-5477cdc2-grp
  locations:
  - us-east4-a
  - us-east4-b
  - us-east4-c
  management:
    autoRepair: true
    autoUpgrade: true
  maxPodsConstraint:
    maxPodsPerNode: '200'
  name: application-np-1
  networkConfig:
    enablePrivateNodes: true
    podIpv4CidrBlock: 240.12.64.0/19
    podIpv4RangeUtilization: 0.0625
    podRange: gke-pods
  podIpv4CidrSize: 23
  selfLink: https://container.googleapis.com/v1/projects/lab-gke-se/locations/us-east4/clusters/gke-std-go76/nodePools/application-np-1
  status: RUNNING
  upgradeSettings:
    maxSurge: 1
    strategy: SURGE
  version: 1.30.5-gke.1014001
notificationConfig:
  pubsub: {}
privateClusterConfig:
  enablePrivateNodes: true
  masterIpv4CidrBlock: 10.252.1.0/28
  privateEndpoint: 10.252.1.2
  publicEndpoint: 34.21.0.111
rbacBindingConfig:
  enableInsecureBindingSystemAuthenticated: true
  enableInsecureBindingSystemUnauthenticated: true
releaseChannel:
  channel: REGULAR
resourceLabels:
  goog-terraform-provisioned: 'true'
secretManagerConfig:
  enabled: true
securityPostureConfig:
  mode: DISABLED
  vulnerabilityMode: VULNERABILITY_DISABLED
selfLink: https://container.googleapis.com/v1/projects/lab-gke-se/locations/us-east4/clusters/gke-std-go76
servicesIpv4Cidr: 240.12.36.0/22
shieldedNodes: {}
status: RUNNING
subnetwork: gke-std-go76
userManagedKeysConfig: {}
verticalPodAutoscaling:
  enabled: true
workloadIdentityConfig:
  workloadPool: lab-gke-se.svc.id.goog
zone: us-east4
