projectId: lab-gke-se
displayName: GKE Cluster Service Account
description: service account for GKE Cluster
email: gke-cluster@lab-gke-se.iam.gserviceaccount.com
name: projects/lab-gke-se/serviceAccounts/gke-cluster@lab-gke-se.iam.gserviceaccount.com
