canIpForward: false
confidentialInstanceConfig:
  enableConfidentialCompute: false
cpuPlatform: Unknown CPU Platform
creationTimestamp: '2024-08-08T23:40:27.903-07:00'
deletionProtection: false
description: ''
disks:
- architecture: X86_64
  autoDelete: true
  boot: true
  deviceName: bastion2
  diskSizeGb: '10'
  guestOsFeatures:
  - type: UEFI_COMPATIBLE
  - type: VIRTIO_SCSI_MULTIQUEUE
  - type: GVNIC
  - type: SEV_CAPABLE
  - type: SEV_LIVE_MIGRATABLE_V2
  index: 0
  interface: SCSI
  kind: compute#attachedDisk
  licenses:
  - https://www.googleapis.com/compute/v1/projects/debian-cloud/global/licenses/debian-12-bookworm
  mode: READ_WRITE
  source: https://www.googleapis.com/compute/v1/projects/lab-gke-se/zones/us-east4-a/disks/bastion2
  type: PERSISTENT
displayDevice:
  enableDisplay: false
fingerprint: 65CKMr67oeA=
id: '4115852903553959732'
keyRevocationActionType: NONE
kind: compute#instance
labelFingerprint: 42WmSpB8rSM=
lastStartTimestamp: '2024-09-25T23:47:44.927-07:00'
lastStopTimestamp: '2024-09-27T07:29:43.390-07:00'
machineType: https://www.googleapis.com/compute/v1/projects/lab-gke-se/zones/us-east4-a/machineTypes/e2-micro
metadata:
  fingerprint: 9f82vypI1zU=
  kind: compute#metadata
name: bastion2
networkInterfaces:
- accessConfigs:
  - kind: compute#accessConfig
    name: External NAT
    networkTier: PREMIUM
    type: ONE_TO_ONE_NAT
  fingerprint: oqc5pm37Gn4=
  kind: compute#networkInterface
  name: nic0
  network: https://www.googleapis.com/compute/v1/projects/lab-gke-se/global/networks/dev-network
  networkIP: 10.10.1.14
  stackType: IPV4_ONLY
  subnetwork: https://www.googleapis.com/compute/v1/projects/lab-gke-se/regions/us-east4/subnetworks/tenant-gke-private
reservationAffinity:
  consumeReservationType: ANY_RESERVATION
satisfiesPzi: true
scheduling:
  automaticRestart: true
  onHostMaintenance: MIGRATE
  preemptible: false
  provisioningModel: STANDARD
selfLink: https://www.googleapis.com/compute/v1/projects/lab-gke-se/zones/us-east4-a/instances/bastion2
shieldedInstanceConfig:
  enableIntegrityMonitoring: true
  enableSecureBoot: false
  enableVtpm: true
shieldedInstanceIntegrityPolicy:
  updateAutoLearnPolicy: true
startRestricted: false
status: TERMINATED
tags:
  fingerprint: 42WmSpB8rSM=
zone: https://www.googleapis.com/compute/v1/projects/lab-gke-se/zones/us-east4-a
