canIpForward: false
cpuPlatform: AMD Rome
creationTimestamp: '2024-06-03T06:36:07.087-07:00'
deletionProtection: false
disks:
- architecture: X86_64
  autoDelete: true
  boot: true
  deviceName: book-disk-glr-1
  diskSizeGb: '11'
  guestOsFeatures:
  - type: UEFI_COMPATIBLE
  - type: VIRTIO_SCSI_MULTIQUEUE
  - type: GVNIC
  - type: SEV_CAPABLE
  index: 0
  interface: SCSI
  kind: compute#attachedDisk
  licenses:
  - https://www.googleapis.com/compute/v1/projects/debian-cloud/global/licenses/debian-11-bullseye
  mode: READ_WRITE
  source: https://www.googleapis.com/compute/v1/projects/lab-gke-se/zones/us-east4-a/disks/proxy
  type: PERSISTENT
fingerprint: 2P_Uh1OWPsE=
id: '5544475699004340265'
kind: compute#instance
labelFingerprint: 42WmSpB8rSM=
lastStartTimestamp: '2024-06-03T06:36:11.410-07:00'
machineType: https://www.googleapis.com/compute/v1/projects/lab-gke-se/zones/us-east4-a/machineTypes/e2-standard-2
metadata:
  fingerprint: 9f82vypI1zU=
  kind: compute#metadata
name: proxy
networkInterfaces:
- fingerprint: 6ns1B8xYs2Y=
  kind: compute#networkInterface
  name: nic0
  network: https://www.googleapis.com/compute/v1/projects/lab-gke-se/global/networks/dev-network
  networkIP: 162.124.14.3
  stackType: IPV4_ONLY
  subnetwork: https://www.googleapis.com/compute/v1/projects/lab-gke-se/regions/us-east4/subnetworks/proxy
satisfiesPzi: true
scheduling:
  automaticRestart: true
  onHostMaintenance: MIGRATE
  preemptible: false
  provisioningModel: STANDARD
selfLink: https://www.googleapis.com/compute/v1/projects/lab-gke-se/zones/us-east4-a/instances/proxy
shieldedInstanceConfig:
  enableIntegrityMonitoring: true
  enableSecureBoot: false
  enableVtpm: true
shieldedInstanceIntegrityPolicy:
  updateAutoLearnPolicy: true
startRestricted: false
status: RUNNING
tags:
  fingerprint: 42WmSpB8rSM=
zone: https://www.googleapis.com/compute/v1/projects/lab-gke-se/zones/us-east4-a
