canIpForward: false
cpuPlatform: Intel Broadwell
creationTimestamp: '2024-06-13T13:43:14.208-07:00'
deletionProtection: false
disks:
- architecture: X86_64
  autoDelete: true
  boot: true
  deviceName: book-disk-glr-1
  diskSizeGb: '11'
  guestOsFeatures:
  - type: UEFI_COMPATIBLE
  - type: VIRTIO_SCSI_MULTIQUEUE
  - type: GVNIC
  - type: SEV_CAPABLE
  index: 0
  interface: SCSI
  kind: compute#attachedDisk
  licenses:
  - https://www.googleapis.com/compute/v1/projects/debian-cloud/global/licenses/debian-11-bullseye
  mode: READ_WRITE
  source: https://www.googleapis.com/compute/v1/projects/lab-gke-se/zones/us-east4-a/disks/pupi
  type: PERSISTENT
fingerprint: AdwUO1A2dk4=
id: '915509240436025102'
kind: compute#instance
labelFingerprint: 42WmSpB8rSM=
lastStartTimestamp: '2024-06-13T13:43:25.142-07:00'
machineType: https://www.googleapis.com/compute/v1/projects/lab-gke-se/zones/us-east4-a/machineTypes/e2-standard-2
metadata:
  fingerprint: 9f82vypI1zU=
  kind: compute#metadata
name: pupi
networkInterfaces:
- fingerprint: x2NS8cgz_68=
  kind: compute#networkInterface
  name: nic0
  network: https://www.googleapis.com/compute/v1/projects/lab-gke-se/global/networks/onpremise
  networkIP: 161.124.14.2
  stackType: IPV4_ONLY
  subnetwork: https://www.googleapis.com/compute/v1/projects/lab-gke-se/regions/us-east4/subnetworks/pupi
satisfiesPzi: true
scheduling:
  automaticRestart: true
  onHostMaintenance: MIGRATE
  preemptible: false
  provisioningModel: STANDARD
selfLink: https://www.googleapis.com/compute/v1/projects/lab-gke-se/zones/us-east4-a/instances/pupi
shieldedInstanceConfig:
  enableIntegrityMonitoring: true
  enableSecureBoot: false
  enableVtpm: true
shieldedInstanceIntegrityPolicy:
  updateAutoLearnPolicy: true
startRestricted: false
status: RUNNING
tags:
  fingerprint: 42WmSpB8rSM=
zone: https://www.googleapis.com/compute/v1/projects/lab-gke-se/zones/us-east4-a
