canIpForward: false
cpuPlatform: Intel Broadwell
creationTimestamp: '2024-06-13T12:55:03.471-07:00'
deletionProtection: false
disks:
- architecture: X86_64
  autoDelete: true
  boot: true
  deviceName: book-disk-glr-1
  diskSizeGb: '11'
  guestOsFeatures:
  - type: UEFI_COMPATIBLE
  - type: VIRTIO_SCSI_MULTIQUEUE
  - type: GVNIC
  - type: SEV_CAPABLE
  index: 0
  interface: SCSI
  kind: compute#attachedDisk
  licenses:
  - https://www.googleapis.com/compute/v1/projects/debian-cloud/global/licenses/debian-11-bullseye
  mode: READ_WRITE
  source: https://www.googleapis.com/compute/v1/projects/lab-gke-se/zones/us-east4-a/disks/vdi
  type: PERSISTENT
fingerprint: OI56p6jfOGQ=
id: '4604867438822486136'
kind: compute#instance
labelFingerprint: 42WmSpB8rSM=
lastStartTimestamp: '2024-06-13T13:16:13.340-07:00'
lastStopTimestamp: '2024-06-13T13:13:29.729-07:00'
machineType: https://www.googleapis.com/compute/v1/projects/lab-gke-se/zones/us-east4-a/machineTypes/e2-standard-2
metadata:
  fingerprint: 9f82vypI1zU=
  kind: compute#metadata
name: vdi
networkInterfaces:
- fingerprint: Vp1y0A846NY=
  kind: compute#networkInterface
  name: nic0
  network: https://www.googleapis.com/compute/v1/projects/lab-gke-se/global/networks/onpremise
  networkIP: 10.10.2.2
  stackType: IPV4_ONLY
  subnetwork: https://www.googleapis.com/compute/v1/projects/lab-gke-se/regions/us-east4/subnetworks/vdi
satisfiesPzi: true
scheduling:
  automaticRestart: true
  onHostMaintenance: MIGRATE
  preemptible: false
  provisioningModel: STANDARD
selfLink: https://www.googleapis.com/compute/v1/projects/lab-gke-se/zones/us-east4-a/instances/vdi
shieldedInstanceConfig:
  enableIntegrityMonitoring: true
  enableSecureBoot: false
  enableVtpm: true
shieldedInstanceIntegrityPolicy:
  updateAutoLearnPolicy: true
startRestricted: false
status: RUNNING
tags:
  fingerprint: 42WmSpB8rSM=
zone: https://www.googleapis.com/compute/v1/projects/lab-gke-se/zones/us-east4-a
