name: projects/52991355109/secrets/certificates
replication:
  userManaged:
    replicas:
    - customerManagedEncryption:
        kmsKeyName: projects/lab-gke-se/locations/us-east4/keyRings/LAB-GKE-SE-gke-key-ring-uudp/cryptoKeys/LAB-GKE-SE-gke-key
      location: us-east4
